### ISSUE TITLE
URL selection change to Map

### ISSUE THREAD

**Issue by svenstm** [almende/eve#12]
Can we change the function of the Agent.getUrls to return a HashMap so I pick the 'right' medium?

**Comment by josdejong** [comment]
That sounds convenient. On the other hand a simple list with urls is more generic and allows for easy filtering/selection in any way (not just on protocol). You can easily write this convenience method for filtering on a protocol, like `List<String> filterUrls(String protocol)`, or a method `String getFirstUrl(String protocol)`. Whatever you need.

**Comment by ludost** [comment]
Won't fix. Too many different selectors can be thought of.
