### ISSUE TITLE
Several classes not found when running on older Android (I am trying 2.2 / api 8)

### ISSUE THREAD

**Issue by tracts-root** [almende/eve#14]
When using Eve on older Android versions, several classes are missing. 

Specifically, the Jackson library wants to load `java.util.concurrent.ConcurrentNavigableMap` but can't find it. This is supposed to be fixed in recent Jackson releases,

https://github.com/FasterXML/jackson-databind/issues/216

... but unfortunately bumping the version in Eve's pom.xml to the latest (2.2.3) did not resolve the issue.

Furthermore, Eve directly relies on `sun.net.www.protocol.file.FileURLConnection` which is apparently also not found on older Android devices. I suppose you could just package a copy of this class along with Eve (if that is allowed licensewise)?

I realize these versions are quite old by now, but unfortunately there are still a lot of people having such devices and we'd really like our app to work for them.

Any suggestions would be much appreciated!

**Comment by ludost** [comment]
The Jackson issue turned out to be a non-issue. FileURLConnection usage has been removed. Another, real problem on old Androids turned out to be the usage of String.isEmpty(), which is not supported by Java <7. All occurrences of this have been removed.
