### ISSUE TITLE
getServletRegistrations() no such method

### ISSUE THREAD

**Issue by svenstm** [almende/eve#16]
When running our agents in a Jetty Server with version: jetty-6.1.24.

I get an which indicates that the getServletRegistrations() doesn't exist. It is called in AgentListener: 34.

I did some research and it appears this function is only available in servlet-api 3.x and this is only added from jetty 8.x. So my question is this function call really needed, because it seems to me that it will only generate a warning? And without we can run it perfectly (tested).

**Comment by ludost** [comment]
This code is not only for generating a warning, it also provides backwards compatibility with the old way init parameters were put in web.xml. I don't think we need to support servlet-api 2.x, so I like to focus on trying to get your project to work with the newer library.
