### ISSUE TITLE
JAVA: Possible bug with @Required(false) parameters

### ISSUE THREAD

**Issue by tracts-root** [almende/eve#21]
I have an Eve agent with a method having two parameters, both of which have the @Required(false) annotation. However if I fire a RPC call with empty parameter object (e.g., by not filling in either value in the web form) then I get an error saying that the second parameter (index 1) must not be null.

Browsing superficially through the code I think the problem may be that the JSON parameter object is mapped to an Object[] by the time JSONRPC.createRequest() is invoked. Apparently this is done based on order/index rather of the various params rather than their names.

I would think this @Name annotation should make it possible to allow "gaps" in the parameter list?

Either way it might be dangerous to map based on the order/index of parameters, because afaik JSON doesn't make guarantees about this.

Thanks for taking a look!

**Comment by tracts-root** [comment]
@ludost As requested, the stack trace:

Error: {
  "code": -32603,
  "message": "java.lang.IllegalArgumentException: Required parameter 1 in method 'getMembersWithResources' is null.",
  "data": {
    "cause": null,
    "stackTrace": [
      {
        "methodName": "createRequest",
        "fileName": "JSONRPC.java",
        "lineNumber": 489,
        "className": "com.almende.eve.rpc.jsonrpc.JSONRPC",
        "nativeMethod": false
      },
      {
        "methodName": "invoke",
        "fileName": "AgentHost.java",
        "lineNumber": 198,
        "className": "com.almende.eve.agent.AgentHost$1",
        "nativeMethod": false
      },
      {
        "methodName": "getMembersWithResources",
        "fileName": null,
        "lineNumber": -1,
        "className": "$Proxy27",
        "nativeMethod": false
      },
      {
        "methodName": "getParentGroupsWithMembers",
        "fileName": "PersonalAgent.java",
        "lineNumber": 200,
        "className": "com.askcs.agents.PersonalAgent",
        "nativeMethod": false
      },
      {
        "methodName": "invoke0",
        "fileName": "NativeMethodAccessorImpl.java",
        "lineNumber": -2,
        "className": "sun.reflect.NativeMethodAccessorImpl",
        "nativeMethod": true
      },
      {
        "methodName": "invoke",
        "fileName": "NativeMethodAccessorImpl.java",
        "lineNumber": 57,
        "className": "sun.reflect.NativeMethodAccessorImpl",
        "nativeMethod": false
      },
      {
        "methodName": "invoke",
        "fileName": "DelegatingMethodAccessorImpl.java",
        "lineNumber": 43,
        "className": "sun.reflect.DelegatingMethodAccessorImpl",
        "nativeMethod": false
      },
      {
        "methodName": "invoke",
        "fileName": "Method.java",
        "lineNumber": 601,
        "className": "java.lang.reflect.Method",
        "nativeMethod": false
      },
      {
        "methodName": "invoke",
        "fileName": "JSONRPC.java",
        "lineNumber": 141,
        "className": "com.almende.eve.rpc.jsonrpc.JSONRPC",
        "nativeMethod": false
      },
      {
        "methodName": "receive",
        "fileName": "AgentHost.java",
        "lineNumber": 339,
        "className": "com.almende.eve.agent.AgentHost",
        "nativeMethod": false
      },
      {
        "methodName": "doPost",
        "fileName": "AgentServlet.java",
        "lineNumber": 309,
        "className": "com.almende.eve.transport.http.AgentServlet",
        "nativeMethod": false
      },
      {
        "methodName": "service",
        "fileName": "HttpServlet.java",
        "lineNumber": 637,
        "className": "javax.servlet.http.HttpServlet",
        "nativeMethod": false
      },
      {
        "methodName": "service",
        "fileName": "HttpServlet.java",
        "lineNumber": 717,
        "className": "javax.servlet.http.HttpServlet",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "ServletHolder.java",
        "lineNumber": 511,
        "className": "org.mortbay.jetty.servlet.ServletHolder",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "ServletHandler.java",
        "lineNumber": 390,
        "className": "org.mortbay.jetty.servlet.ServletHandler",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "SecurityHandler.java",
        "lineNumber": 216,
        "className": "org.mortbay.jetty.security.SecurityHandler",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "SessionHandler.java",
        "lineNumber": 182,
        "className": "org.mortbay.jetty.servlet.SessionHandler",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "ContextHandler.java",
        "lineNumber": 766,
        "className": "org.mortbay.jetty.handler.ContextHandler",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "WebAppContext.java",
        "lineNumber": 418,
        "className": "org.mortbay.jetty.webapp.WebAppContext",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "ContextHandlerCollection.java",
        "lineNumber": 230,
        "className": "org.mortbay.jetty.handler.ContextHandlerCollection",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "HandlerCollection.java",
        "lineNumber": 114,
        "className": "org.mortbay.jetty.handler.HandlerCollection",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 152,
        "className": "org.mortbay.jetty.handler.HandlerWrapper",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "Server.java",
        "lineNumber": 326,
        "className": "org.mortbay.jetty.Server",
        "nativeMethod": false
      },
      {
        "methodName": "handleRequest",
        "fileName": "HttpConnection.java",
        "lineNumber": 542,
        "className": "org.mortbay.jetty.HttpConnection",
        "nativeMethod": false
      },
      {
        "methodName": "content",
        "fileName": "HttpConnection.java",
        "lineNumber": 943,
        "className": "org.mortbay.jetty.HttpConnection$RequestHandler",
        "nativeMethod": false
      },
      {
        "methodName": "parseNext",
        "fileName": "HttpParser.java",
        "lineNumber": 756,
        "className": "org.mortbay.jetty.HttpParser",
        "nativeMethod": false
      },
      {
        "methodName": "parseAvailable",
        "fileName": "HttpParser.java",
        "lineNumber": 218,
        "className": "org.mortbay.jetty.HttpParser",
        "nativeMethod": false
      },
      {
        "methodName": "handle",
        "fileName": "HttpConnection.java",
        "lineNumber": 404,
        "className": "org.mortbay.jetty.HttpConnection",
        "nativeMethod": false
      },
      {
        "methodName": "run",
        "fileName": "SelectChannelEndPoint.java",
        "lineNumber": 410,
        "className": "org.mortbay.io.nio.SelectChannelEndPoint",
        "nativeMethod": false
      },
      {
        "methodName": "run",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 582,
        "className": "org.mortbay.thread.QueuedThreadPool$PoolThread",
        "nativeMethod": false
      }
    ],
    "message": "Required parameter 1 in method 'getMembersWithResources' is null.",
    "localizedMessage": "Required parameter 1 in method 'getMembersWithResources' is null.",
    "suppressed": []
  }
}

**Comment by ludost** [comment]
Hi Erik,
I've tried to reproduce your results, but to no effect. I can call such method without problems with 0, 1 or 2 parameter values, in any order. Maybe you can send me a code sample of how you defined your method?
