### ISSUE TITLE
Http Calls fail

### ISSUE THREAD

**Issue by svenstm** [almende/eve#22]
Everyone once in a while an http call fails to an external agent. The error I receive is this:

Error: {
  "code": 0,
  "message": "Failed to send RPC call through HTTP",
  "data": "{\"cause\":null,\"stackTrace\":[{\"methodName\":\"parseHead\",\"fileName\":\"DefaultHttpResponseParser.java\",\"lineNumber\":95,\"className\":\"org.apache.http.impl.conn.DefaultHttpResponseParser\",\"nativeMethod\":false},{\"methodName\":\"parseHead\",\"fileName\":\"DefaultHttpResponseParser.java\",\"lineNumber\":62,\"className\":\"org.apache.http.impl.conn.DefaultHttpResponseParser\",\"nativeMethod\":false},{\"methodName\":\"parse\",\"fileName\":\"AbstractMessageParser.java\",\"lineNumber\":254,\"className\":\"org.apache.http.impl.io.AbstractMessageParser\",\"nativeMethod\":false},{\"methodName\":\"receiveResponseHeader\",\"fileName\":\"AbstractHttpClientConnection.java\",\"lineNumber\":289,\"className\":\"org.apache.http.impl.AbstractHttpClientConnection\",\"nativeMethod\":false},{\"methodName\":\"receiveResponseHeader\",\"fileName\":\"DefaultClientConnection.java\",\"lineNumber\":252,\"className\":\"org.apache.http.impl.conn.DefaultClientConnection\",\"nativeMethod\":false},{\"methodName\":\"receiveResponseHeader\",\"fileName\":\"ManagedClientConnectionImpl.java\",\"lineNumber\":191,\"className\":\"org.apache.http.impl.conn.ManagedClientConnectionImpl\",\"nativeMethod\":false},{\"methodName\":\"doReceiveResponse\",\"fileName\":\"HttpRequestExecutor.java\",\"lineNumber\":300,\"className\":\"org.apache.http.protocol.HttpRequestExecutor\",\"nativeMethod\":false},{\"methodName\":\"execute\",\"fileName\":\"HttpRequestExecutor.java\",\"lineNumber\":127,\"className\":\"org.apache.http.protocol.HttpRequestExecutor\",\"nativeMethod\":false},{\"methodName\":\"tryExecute\",\"fileName\":\"DefaultRequestDirector.java\",\"lineNumber\":717,\"className\":\"org.apache.http.impl.client.DefaultRequestDirector\",\"nativeMethod\":false},{\"methodName\":\"execute\",\"fileName\":\"DefaultRequestDirector.java\",\"lineNumber\":522,\"className\":\"org.apache.http.impl.client.DefaultRequestDirector\",\"nativeMethod\":false},{\"methodName\":\"execute\",\"fileName\":\"AbstractHttpClient.java\",\"lineNumber\":906,\"className\":\"org.apache.http.impl.client.AbstractHttpClient\",\"nativeMethod\":false},{\"methodName\":\"execute\",\"fileName\":\"AbstractHttpClient.java\",\"lineNumber\":805,\"className\":\"org.apache.http.impl.client.AbstractHttpClient\",\"nativeMethod\":false},{\"methodName\":\"execute\",\"fileName\":\"AbstractHttpClient.java\",\"lineNumber\":784,\"className\":\"org.apache.http.impl.client.AbstractHttpClient\",\"nativeMethod\":false},{\"methodName\":\"send\",\"fileName\":\"HttpService.java\",\"lineNumber\":137,\"className\":\"com.almende.eve.transport.http.HttpService\",\"nativeMethod\":false},{\"methodName\":\"send\",\"fileName\":\"AgentHost.java\",\"lineNumber\":380,\"className\":\"com.almende.eve.agent.AgentHost\",\"nativeMethod\":false},{\"methodName\":\"invoke\",\"fileName\":\"AgentHost.java\",\"lineNumber\":200,\"className\":\"com.almende.eve.agent.AgentHost$1\",\"nativeMethod\":false},{\"methodName\":\"registerAgent\",\"fileName\":null,\"lineNumber\":-1,\"className\":\"com.sun.proxy.$Proxy29\",\"nativeMethod\":false},{\"methodName\":\"registerXmppAccount\",\"fileName\":\"DomainAgent.java\",\"lineNumber\":379,\"className\":\"com.askcs.agents.DomainAgent\",\"nativeMethod\":false},{\"methodName\":\"addMonitorAgent\",\"fileName\":\"DomainAgent.java\",\"lineNumber\":428,\"className\":\"com.askcs.agents.DomainAgent\",\"nativeMethod\":false},{\"methodName\":\"invoke0\",\"fileName\":\"NativeMethodAccessorImpl.java\",\"lineNumber\":-2,\"className\":\"sun.reflect.NativeMethodAccessorImpl\",\"nativeMethod\":true},{\"methodName\":\"invoke\",\"fileName\":\"NativeMethodAccessorImpl.java\",\"lineNumber\":57,\"className\":\"sun.reflect.NativeMethodAccessorImpl\",\"nativeMethod\":false},{\"methodName\":\"invoke\",\"fileName\":\"DelegatingMethodAccessorImpl.java\",\"lineNumber\":43,\"className\":\"sun.reflect.DelegatingMethodAccessorImpl\",\"nativeMethod\":false},{\"methodName\":\"invoke\",\"fileName\":\"Method.java\",\"lineNumber\":606,\"className\":\"java.lang.reflect.Method\",\"nativeMethod\":false},{\"methodName\":\"invoke\",\"fileName\":\"JSONRPC.java\",\"lineNumber\":141,\"className\":\"com.almende.eve.rpc.jsonrpc.JSONRPC\",\"nativeMethod\":false},{\"methodName\":\"receive\",\"fileName\":\"AgentHost.java\",\"lineNumber\":339,\"className\":\"com.almende.eve.agent.AgentHost\",\"nativeMethod\":false},{\"methodName\":\"doPost\",\"fileName\":\"AgentServlet.java\",\"lineNumber\":309,\"className\":\"com.almende.eve.transport.http.AgentServlet\",\"nativeMethod\":false},{\"methodName\":\"service\",\"fileName\":\"HttpServlet.java\",\"lineNumber\":637,\"className\":\"javax.servlet.http.HttpServlet\",\"nativeMethod\":false},{\"methodName\":\"service\",\"fileName\":\"HttpServlet.java\",\"lineNumber\":717,\"className\":\"javax.servlet.http.HttpServlet\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"ServletHolder.java\",\"lineNumber\":511,\"className\":\"org.mortbay.jetty.servlet.ServletHolder\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"ServletHandler.java\",\"lineNumber\":390,\"className\":\"org.mortbay.jetty.servlet.ServletHandler\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"SecurityHandler.java\",\"lineNumber\":216,\"className\":\"org.mortbay.jetty.security.SecurityHandler\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"SessionHandler.java\",\"lineNumber\":182,\"className\":\"org.mortbay.jetty.servlet.SessionHandler\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"ContextHandler.java\",\"lineNumber\":766,\"className\":\"org.mortbay.jetty.handler.ContextHandler\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"WebAppContext.java\",\"lineNumber\":418,\"className\":\"org.mortbay.jetty.webapp.WebAppContext\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"ContextHandlerCollection.java\",\"lineNumber\":230,\"className\":\"org.mortbay.jetty.handler.ContextHandlerCollection\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"HandlerCollection.java\",\"lineNumber\":114,\"className\":\"org.mortbay.jetty.handler.HandlerCollection\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"HandlerWrapper.java\",\"lineNumber\":152,\"className\":\"org.mortbay.jetty.handler.HandlerWrapper\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"Server.java\",\"lineNumber\":326,\"className\":\"org.mortbay.jetty.Server\",\"nativeMethod\":false},{\"methodName\":\"handleRequest\",\"fileName\":\"HttpConnection.java\",\"lineNumber\":542,\"className\":\"org.mortbay.jetty.HttpConnection\",\"nativeMethod\":false},{\"methodName\":\"content\",\"fileName\":\"HttpConnection.java\",\"lineNumber\":943,\"className\":\"org.mortbay.jetty.HttpConnection$RequestHandler\",\"nativeMethod\":false},{\"methodName\":\"parseNext\",\"fileName\":\"HttpParser.java\",\"lineNumber\":756,\"className\":\"org.mortbay.jetty.HttpParser\",\"nativeMethod\":false},{\"methodName\":\"parseAvailable\",\"fileName\":\"HttpParser.java\",\"lineNumber\":218,\"className\":\"org.mortbay.jetty.HttpParser\",\"nativeMethod\":false},{\"methodName\":\"handle\",\"fileName\":\"HttpConnection.java\",\"lineNumber\":404,\"className\":\"org.mortbay.jetty.HttpConnection\",\"nativeMethod\":false},{\"methodName\":\"run\",\"fileName\":\"SelectChannelEndPoint.java\",\"lineNumber\":410,\"className\":\"org.mortbay.io.nio.SelectChannelEndPoint\",\"nativeMethod\":false},{\"methodName\":\"run\",\"fileName\":\"QueuedThreadPool.java\",\"lineNumber\":582,\"className\":\"org.mortbay.thread.QueuedThreadPool$PoolThread\",\"nativeMethod\":false}],\"message\":\"The target server failed to respond\",\"localizedMessage\":\"The target server failed to respond\",\"suppressed\":[]}"
}

I've also narrowed the problem down to this:
http://stackoverflow.com/questions/10558791/apache-httpclient-interim-error-nohttpresponseexception

**Comment by ludost** [comment]
preliminary results show it is fixed with latest change.
