### ISSUE TITLE
JSONRPCException: Couldn't handle XMPP return causing Android ANR errors

### ISSUE THREAD

**Issue by Jordi-m** [almende/eve#27]
De volgende error zorgt ervoor dat de app een ANR (Application Not Respoding) error geeft als je deze hebt geopend, maar al een tijdje niet gebruikt (bijv telefoon in standby modus of andere apps eroverheen), als je dan terug komt in de app lijkt er iets mis te gaan met de verbinding terwijl de XMPP verbinding wel wordt gebruikt.

The following errors cause our Android app to throw an ANR error (Application Not Responding), which seem to happen if something 'above' app level goes wrong (not 100% sure though). The error is hard to reproduce, but most of the times it happens when the app has been inactive for a while (couple of hours or a full day) and is then resumed. It can also happen now and then when another app is opened over our app and that one is closed; when returning to our app (onresume) the error is sometimes shown. It seems to be an issue with the state of the XMPP connection at that very moment.

As far as I know it may be caused by the callback.get() in the XmppService.java class, which seems to be 'blocking' for a while (because of a [not yet] exisiting XMPP connection?)

EVE version: **2.1.0-SNAPSHOT**

If anyone has seen such errors before or has a solution, please let us know.

_Stacktrace:_
[testuser@xmpp.ask-cs.com/cloud was only, in the cloud, at the time the error occured in the mobile app]

02-05 16:45:32.817  13097-13097/com.askcs.standby W/System.err? java.lang.reflect.UndeclaredThrowableException
02-05 16:45:32.822  13097-13097/com.askcs.standby W/System.err? at $Proxy8.getId(Native Method)
02-05 16:45:32.822  13097-13097/com.askcs.standby W/System.err? at com.askcs.standby.common.MainService.onResumed(MainService.java:653)
02-05 16:45:32.827  13097-13097/com.askcs.standby W/System.err? at java.lang.reflect.Method.invokeNative(Native Method)
02-05 16:45:32.827  13097-13097/com.askcs.standby W/System.err? at java.lang.reflect.Method.invoke(Method.java:511)
02-05 16:45:32.832  13097-13097/com.askcs.standby W/System.err? at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
02-05 16:45:32.832  13097-13097/com.askcs.standby W/System.err? at com.squareup.otto.Bus.dispatch(Bus.java:372)
02-05 16:45:32.837  13097-13097/com.askcs.standby W/System.err? at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:355)
02-05 16:45:32.842  13097-13097/com.askcs.standby W/System.err? at com.squareup.otto.Bus.post(Bus.java:324)
02-05 16:45:32.842  13097-13097/com.askcs.standby W/System.err? at com.askcs.standby.util.BusProvider$1.post(BusProvider.java:45)
02-05 16:45:32.847  13097-13097/com.askcs.standby W/System.err? at com.askcs.standby.common.StandByActivity.onResume(StandByActivity.java:77)
02-05 16:45:32.847  13097-13097/com.askcs.standby W/System.err? at com.askcs.standby.common.MainActivity.onResume(MainActivity.java:361)
02-05 16:45:32.852  13097-13097/com.askcs.standby W/System.err? at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
02-05 16:45:32.852  13097-13097/com.askcs.standby W/System.err? at android.app.Activity.performResume(Activity.java:5280)
02-05 16:45:32.857  13097-13097/com.askcs.standby W/System.err? at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
02-05 16:45:32.857  13097-13097/com.askcs.standby W/System.err? at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
02-05 16:45:32.862  13097-13097/com.askcs.standby W/System.err? at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
02-05 16:45:32.867  13097-13097/com.askcs.standby W/System.err? at android.os.Handler.dispatchMessage(Handler.java:99)
02-05 16:45:32.872  13097-13097/com.askcs.standby W/System.err? at android.os.Looper.loop(Looper.java:137)
02-05 16:45:32.872  13097-13097/com.askcs.standby W/System.err? at android.app.ActivityThread.main(ActivityThread.java:4921)
02-05 16:45:32.887  13097-13097/com.askcs.standby W/System.err? at java.lang.reflect.Method.invokeNative(Native Method)
02-05 16:45:32.887  13097-13097/com.askcs.standby W/System.err? at java.lang.reflect.Method.invoke(Method.java:511)
02-05 16:45:32.887  13097-13097/com.askcs.standby W/System.err? at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
02-05 16:45:32.892  13097-13097/com.askcs.standby W/System.err? at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
02-05 16:45:32.892  13097-13097/com.askcs.standby W/System.err? at dalvik.system.NativeStart.main(Native Method)
02-05 16:45:32.897  13097-13097/com.askcs.standby W/System.err? Caused by: com.almende.eve.rpc.jsonrpc.JSONRPCException: Couldn't handle XMPP return.
02-05 16:45:32.912  13097-13097/com.askcs.standby W/System.err? at com.almende.eve.transport.xmpp.XmppService.send(XmppService.java:389)
02-05 16:45:32.912  13097-13097/com.askcs.standby W/System.err? at com.almende.eve.agent.AgentHost.send(AgentHost.java:390)
02-05 16:45:32.917  13097-13097/com.askcs.standby W/System.err? at com.almende.eve.agent.AgentHost$1.invoke(AgentHost.java:203)
02-05 16:45:32.922  13097-13097/com.askcs.standby W/System.err? ... 24 more
02-05 16:45:32.922  13097-13097/com.askcs.standby W/System.err? Caused by: java.util.concurrent.TimeoutException: Timeout occurred for request with id '7a156c00-8e7c-11e3-9f6b-00007f000001': testuser@xmpp.ask-cs.com/cloud -> getId
02-05 16:45:32.927  13097-13097/com.askcs.standby W/System.err? at com.almende.eve.agent.callback.AsyncCallbackQueue$1.run(AsyncCallbackQueue.java:52)
02-05 16:45:32.927  13097-13097/com.askcs.standby W/System.err? at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by ludost** [comment]
The callback you mentioned is blocking, but should always run in a background thread. (where it is allowed to be slow) To get to an ANR, you need to be doing something that blocks the foreground thread. If this is related to the XMPP timeout depends on how you designed the communication between foreground and background threads. Are you using our original app design? (The one I created for BRIDGE?) In that case I would expect some issues in accessing the State, as that is the only potentially slow code in the foreground.

**Comment by ludost** [comment]
Hi Jordi, any news on this issue?

**Comment by Jordi-m** [comment]
Hi. Currently not. I haven't seen the error on my own phones for a while, I'm not sure if users still experience this issue. During the last 30 days only 1 ANR error was reported in the Google Play Store publisher dashboard.

Currently I'm trying to upgrade our EVE dependency to 2.2.1-SNAPSHOT (in preparation for the upcoming release) and make it compatible with our AskPack. I heard a lot of things changed, so we'll see if this issue will this exist after the upgrade.

**Comment by ludost** [comment]
ok, for now I close this issue. If you run into similar issues, let me know.
