### ISSUE TITLE
Adding External Jars

### ISSUE THREAD

**Issue by christos89** [almende/eve#30]
Hallo,
I am trying to add some external JAR files in the Eve project. I am using Eclipse and  I have added the path of the JAR files in the CLASSPATH and the Path environment variables and also added the reference library in the preferences of Eclipse. This error occurs: ClassNotFoundException . I have tried a lot of stuff but no solution. Finally, I saw also that I may have to configure a MANIFEST.TXT  file. I 'm not sure which file this is in case of an eve application (maybe eve.yaml?) 

Do you have any idea what I can do?

Thank you in advance,
Regards,

Christos

**Comment by ludost** [comment]
Hi Christos,
As this question is not Eve related, I'll answer it through normal email. (later today)
Greetings,
Ludo.

**Comment by christos89** [comment]
Ok thanks a lot!
