### ISSUE TITLE
IllegalStateException in JSONRPC.init()

### ISSUE THREAD

**Issue by tracts-root** [almende/eve#33]
Hi,

I think there is a problem with the constructor
`JSONRPC(CODE, String, Throwable)`

This calls the super-constructor with description and throwable (second and third) argument but then also passes the throwable into the `init( CODE, String, Throwable )` method, which will attempt to call `initCause( throwable )` but that results in a `IllegalStateException`. From the java docs for `initCause`:

`IllegalStateException` - if this throwable was created with `Throwable(Throwable)` or `Throwable(String,Throwable)`, or this method has already been called on this throwable.

So it looks like if we call the super-class constructor with an exception or throwable then we can't call initCause. Which makes sense, I think, probably the solution is to never pass the throwable argument to the superclass constructor but always let the `init` function initialize the cause.

**Comment by tracts-root** [comment]
Figured I would just confirm: simply omitting the `throwable` argument from the `super` call works fine. So that would read

```
public JSONRPCException(final CODE code, final String description, final Throwable t) {
    super(description);
    init(code, description, t);
}
```

**Comment by ludost** [comment]
Hi Erik,

Which release/version are you referring to? In the Master I've done a fix that probably fixes your mentioned issue, but it had not been ported back to 2.2.1 as it was contained in a larger unrelated commit. I'll patch 2.2.1 now, can you check if that helps?

**Comment by tracts-root** [comment]
Hi Ludo,

Thanks! I think the extra clause you added to `init()`, namely to check that `getCause() == null` before attempting to call `initCause` should work fine in most cases. However if we called the `JSONRPCException` constructor with the `Throwable` argument set to `null` (which according to the java docs is actually a reasonable thing to do) then it will still go wrong.

This latter cornercase might be a minor advantage of my suggested fix -- simply not passing the `t` argument to the super constructor -- compared to this extra test inside `init`.

**Comment by tracts-root** [comment]
@ludost Sorry didn't mean to close it just yet, at least until you read my comment :-)

**Comment by tracts-root** [comment]
@ludost Looking at the source for `Throwable` it looks like the test `getCause()==null` will _not_ work... http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/java/lang/Throwable.java#Throwable
The cause field is initialized to `this`, not `null`, so I expect your test will not do what it should when one of the constructors without a throwable is used.

So I guess the way to get this working properly for all constructor variants is not to pass any throwable to the super constructor and remove the `getCause()` test from `init`?

**Comment by ludost** [comment]
The problem is that `super(t)` is different than `setCause(t)`. And I like to have the behaviour of `super(t)` :) 

But back to your statement, which is incorrect: the `getCause()==null` will work:

```
public synchronized Throwable getCause() {
     return (cause==this ? null : cause);
}
```

So, please test my latest commit in your code, I believe it will fix the issue.

PS: I fail to see why putting a null-cause would lead to a problem? Throwable seems to handle that case correctly in its constructors and hopefully JSONRPCException as well.

**Comment by tracts-root** [comment]
Ah, I had not noticed this quirk in `getCause`. I did test it, actually, and my immediate problem is resolved. I still wonder about calling a constructor with `t==null` but as far as I know we're not doing that.

Thanks!

Oh and just curious, what is the difference between `super(t)` and `setCause(t)` that you mentioned?

**Comment by ludost** [comment]
An indication about the safety of the constructors is this statement from one of these constructors:

```
 detailMessage = (cause==null ? null : cause.toString());
```

Which explicitly checks for null causes.
