### ISSUE TITLE
EVE 2.2.0 setRemoveOnCancelPolicy error on Android < 4.4

### ISSUE THREAD

**Issue by Jordi-m** [almende/eve#35]
The latest EVE version (2.2.0_release branch) contains a method/class which is available in Java since version 1.7. Most Android devices, except the newest ones, use Java 1.6 though.

A Fatal Exception/IllegalAccessError is thrown when starting up an app using this EVE version where the Android version is below 4.4. Currently it's only working for my Nexus 5, where Samsung SII devices will fail to start (instant error after startup).

The stacktrace:

```
04-01 11:02:01.904: E/AndroidRuntime(7743): FATAL EXCEPTION: com.askcs.alarmapp.bhv.EveService
04-01 11:02:01.904: E/AndroidRuntime(7743): java.lang.ExceptionInInitializerError
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.AgentHostDefImpl.getCallbackQueue(AgentHostDefImpl.java:874)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.Agent.constr(Agent.java:139)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.AgentHostDefImpl.getAgent(AgentHostDefImpl.java:171)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.AgentHostDefImpl.signalAgents(AgentHostDefImpl.java:109)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.AgentHostDefImpl.setStateFactory(AgentHostDefImpl.java:620)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.askcs.alarmapp.bhv.EveService$1.run(EveService.java:129)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at android.os.Handler.handleCallback(Handler.java:615)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at android.os.Handler.dispatchMessage(Handler.java:92)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at android.os.Looper.loop(Looper.java:137)
04-01 11:02:01.904: E/AndroidRuntime(7743):     at android.os.HandlerThread.run(HandlerThread.java:60)
04-01 11:02:01.904: E/AndroidRuntime(7743): Caused by: java.lang.IllegalAccessError: tried to access method java.util.concurrent.ScheduledThreadPoolExecutor.setRemoveOnCancelPolicy:()V from class com.almende.eve.agent.callback.AsyncCallbackQueue
04-01 11:02:01.904: E/AndroidRuntime(7743):     at com.almende.eve.agent.callback.AsyncCallbackQueue.<clinit>(AsyncCallbackQueue.java:27)
04-01 11:02:01.904: E/AndroidRuntime(7743):     ... 10 more
```

Line 129 in our EveService.java code:

```
_host.setStateFactory(new FileStateFactory(params));
```

It seems like the AsyncCallbackQueue is used somewhere internally here, which triggers the following code to be called in AsyncCallbackQueue.java on line 27

```
scheduler.setRemoveOnCancelPolicy(true);
```

... and this method exists only since Java 1.7.

Let me know if you need an APK/source for reproducing this.

We already tried to (partically) recreate the setRemoveOnCancelPolicy by extending this call. We couldn't get this done due to must restrictions on the code (private/protected methods/vars)

Also setting the JDK compiler to 1.7 did not fix the issue on onder Android devices.

**Comment by ludost** [comment]
I'll see if I can add a check around it for the existence of that method.

**Comment by ludost** [comment]
Can you check the latest commit to the release branch? It should protect against this issue...

**Comment by Jordi-m** [comment]
Thank you for the quick fix. The updated version of EVE does (still) work on the Nexus 5 and now also the Samsung SII, but for Android 2.2 it's still broken. This may be due to our use of Proguard, I'll take a look at that right now. If that doesn't work, I'll let you know.

FYI the current error on a HTC Wildfire running Android 2.2.1.

```
04-02 13:55:46.219    1013-1021/com.askcs.standby E/AndroidRuntime﹕ FATAL EXCEPTION: com.askcs.standby.common.MainService_fg
    java.lang.NoSuchMethodError: java.io.IOException.<init>
            at com.almende.eve.transport.xmpp.AgentConnection.connect(AgentConnection.java:161)
            at com.almende.eve.transport.xmpp.XmppService.connect(XmppService.java:307)
            at com.almende.eve.transport.xmpp.XmppService.reconnect(XmppService.java:564)
            at com.almende.eve.agent.Agent.signalAgent(Agent.java:254)
            at com.almende.eve.agent.AgentHostDefImpl.signalAgents(AgentHostDefImpl.java:111)
            at com.almende.eve.agent.AgentHostDefImpl.addTransportService(AgentHostDefImpl.java:757)
            at com.askcs.standby.common.MainService$2.run(MainService.java:409)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:143)
            at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Update**:

I guess it's unrelated to our use of Proguard, because that should have caused the same issues on Android 4.4 devices, which it doesn't.

**Instant update**:

Seems like it was a Proguard problem for some reason.

I've added these two Proguard exceptions in our configuration. Not sure if they are both necessary (in our configuration the second one is probably already kept):

```
-keep class java.util.concurrent.ConcurrentNavigableMap.** { *; }
```

~~-keep class com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.*\* { *; }~~

**Comment by Jordi-m** [comment]
@ludost I updated my previous comment. For now it seems like the fix solved our problem. Thank you!

Although the error is still displayed in logcat, the app does not crash:

```
04-02 14:19:29.649    1328-1338/com.askcs.standby E/dalvikvm﹕ Could not find class 'java.util.concurrent.ConcurrentNavigableMap', referenced from method com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.<clinit>
```

**Comment by ludost** [comment]
Thanks!
