### ISSUE TITLE
Create/Destroy eve agents through methods

### ISSUE THREAD

**Issue by christos89** [almende/eve#36]
Hallo,

Until now I can create or destroy an eve agent only though Postman or Restclient.  Can somebody explain me how I can do that in a method of an agent? Is that possible?

Thank you in advance,

Kind regards,

Christos Pampidis

**Comment by ludost** [comment]
AgentHost host = AgentHost.getInstance();
host.createAgent(Class<T> agentType,String agentId);
host.deleteAgent(String agentId);

Greetings,
Ludo.
