### ISSUE TITLE
Data is not made persistent.

### ISSUE THREAD

**Issue by svenstm** [almende/eve#4]
When data is stored in context of an agent and the agent is neatly destroyed the agent isn't made persistent. Because if I terminate the gae and restart it again (locally). The data is gone.

My suspisicion is that it is the default delay of GAE to make the data persistent is the in the way.

**Comment by ludost** [comment]
Hi Sven, is this old bug still relevant?

**Comment by ludost** [comment]
ok, after discussing this with Sven I've decided to close this issue. It happens on forcefully closing of the server before data is made persistent, which is a design issue with GAE en Twig. I know a trick to force this (reading the same value directly again), but that will slow down the GAE State significantly. In normal usage this doesn't occur, servers are brought down correctly in that case.
