### ISSUE TITLE
Unable to override AgentServlet methods and fields

### ISSUE THREAD

**Issue by krevelen** [almende/eve#8]
I would like to override servlet_url, config, etc. as specified in the web.xml init and context parameters, but the methods and fields are private (not protected) so I can only override the whole servlet which would cause compatibility issues with future EVE distributions

**Comment by josdejong** [comment]
should already be fixed, see https://github.com/almende/eve/commit/341f62d72d41bf0b7708c6742c27675ae6f42b0c

**Comment by ludost** [comment]
Can this be closed?

**Comment by krevelen** [comment]
OK to close.

2013/9/19 Ludo Stellingwerff notifications@github.com
