### ISSUE TITLE
JDBC/JPA State Factory?

### ISSUE THREAD

**Issue by krevelen** [almende/eve#9]
Given that I would like to have agent states persist beyond the AgentServlet lifetime, a JDBCStateFactory, preferable based on Java Persistence API 2.0, would be much appreciated :-)

**Comment by ludost** [comment]
JDBCStateFactory is a good idea, added to Trello wishlist. But in the meantime, can't you just use the FileStateFactory?

**Comment by josdejong** [comment]
this would indeed be a great addition. I think that using a database to store the agents states (instead of using files) will give better performance, and the database will resolve resource locking for us (which is quite hard to get right on file system level).

**Comment by krevelen** [comment]
Yes FileStateFactory will do for now, but i'm glad to hear a JDBC/JPA implementation is on the wishlist
